language: node_js
node_js:
  - 12
  - 10
  - 8
services: mongodb
before_script:
  - mongo test_lucid --eval 'db.createUser({user:"test",pwd:"test",roles:["dbOwner"]});'
script:
  - DB=mongodb DB_NAME=test_lucid DB_USER=test DB_PASSWORD=test npm test
